### ISSUE TITLE
Report generation broken on Mac

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-coverage#376]
```
Downloading artifacts from 250/257 test task...
Traceback (most recent call last):
  File "codecoverage.py", line 480, in <module>
    main()
  File "codecoverage.py", line 473, in main
    generate_report(grcov_path, "lcov", "output.info", artifact_paths)
  File "codecoverage.py", line 260, in generate_report
    proc = subprocess.Popen(cmd, stdout=fout, stderr=subprocess.PIPE, env=mod_env)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: './grcov'
```

**Comment by marco-c** [comment]
Probably we just need to download the right grcov for the platform where the script is run.

**Comment by marco-c** [comment]
`report` has been retired.
